---
name: CI

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    name: docker-compose
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Start assets
      run: docker-compose up -d assets
    - name: Build
      run: docker-compose build test
    - name: Migrate db
      run: docker-compose run test bundle exec hanami db migrate
    - name: Run tests
      run: docker-compose run test bundle exec rake spec

  build:
    runs-on: ubuntu-latest
    name: buildx + docker-compose
    env:
      DOCKER_IMAGE: "solnic/hanami-blog"
      DOCKER_TAG: ${{ github.sha }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master
      with:
        install: true
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: ${{ runner.os }}-buildx
    - name: Build test image
      uses: docker/build-push-action@v2
      with:
        context: .
        builder: ${{ steps.buildx.outputs.name }}
        tags: ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
        file: Dockerfile
        target: test
        push: false
        load: true
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
    - name: Run tests
      run: docker-compose run --rm test bundle exec rake spec
    # this is needed otherwise the cache would grow until hitting disk space limit
    - name: Move buildx cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
